### ISSUE TITLE
flutterApp/build/flutter_reactive_ble/generated/source/proto/debug/javalite/com/signify/hue/flutterreactiveble/ProtobufModel.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by 0100101101001011** [PhilipsHue/flutter_reactive_ble#134]
When building for Andriod:

```
Note: /Users/user/project1/FlutterProject1/build/flutter_reactive_ble/generated/source/proto/debug/javalite/com/signify/hue/flutterreactiveble/ProtobufModel.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.
```
I am also using firebase plugins. It seems like there is a conflict.

`java.lang.RuntimeException: Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0) and jetified-protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)`

This is my pubspec.yaml dependencies:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^2.5.0
  url_launcher: ^5.7.2
  flutter_svg: ^0.19.0
  flutter_spinkit: ^4.1.2+1
  sembast: ^2.4.7+7
  path_provider: ^1.6.18
  page_transition: ^1.1.7+2
  flutter_circle_color_picker: ^0.2.0
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  carousel_slider: ^2.3.1
```

This is my android/app/build.gradle:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.project1"
        minSdkVersion 24
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    // Import the Firebase BoM
    implementation platform('com.google.firebase:firebase-bom:25.12.0')

    // Add the dependency for the Firebase SDK for Google Analytics
    // When using the BoM, don't specify versions in Firebase dependencies
    implementation 'com.google.firebase:firebase-analytics'

    // Add the dependencies for any other desired Firebase products
    // https://firebase.google.com/docs/android/setup#available-libraries
}

```
