### ISSUE TITLE
ScanFailure on android

### ISSUE THREAD

**Issue by carlos-labrador** [PhilipsHue/flutter_reactive_ble#195]
**Describe the bug**
After integrating FlutterFire package into our project , we are getting the following exception

`REACTIVE_BLE: Received ScanResult(result: Result<DiscoveredDevice, GenericFailure<ScanFailure>>.failure(GenericFailure<ScanFailure>(code: ScanFailure.unknown, message: "Scanning parameters are not set")))
I/flutter (14507): Exception: GenericFailure<ScanFailure>(code: ScanFailure.unknown, message: "Scanning parameters are not set")`
<details><summary>Pub Specs:</summary>

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.5.3"
  flutter_localizations:
    sdk: flutter
  flutter_reactive_ble: ^2.7.1
  firebase_messaging: "^8.0.0-dev.10"
```
</details>

**To Reproduce**
1. Initialize FlutterReactiveBle
2. if it is ready shows Bluetooth Scan page.
3. Users tap on scan button.

**Expected behavior**
it should show all available Bluetooth devices.

**Smartphone*
 - Device: [Samsung s7 edge]
 - OS: [Android 8]
 - Package version: [^2.7.1]

**Peripheral device**
- Vendor, model: [SC-02H]
- Does it run a custom firmware / software: n/a

**Additional context**
I could reproduce it on the base example app adding flutter fire package.
