### ISSUE TITLE
Duplicate declarations of permission android.permission.ACCESS_COARSE_LOCATION with different maxSdkVersions

### ISSUE THREAD

**Issue by clockwork189** [PhilipsHue/flutter_reactive_ble#560]
**Describe the bug**
Hello, I am building an app that is targeting SDK 31 on Android. I am using this plugin along side a location tracking plugin(flutter_background_location). The location tracking plugin automatically adds permissions for COARSE and FINE location, however it seems like when I try to publish a built aab file to the android app store. I get the error of: 
**Duplicate declarations of permission android.permission.ACCESS_COARSE_LOCATION with different maxSdkVersions**

**To Reproduce**
1. Add another location tracking plugin such as flutter_background_location or geolocator, along side flutter_reactive_ble.
2. Run the app (it will run fine in debug mode).
3. Run flutter build appbundle
4. Upload app bundle to google play appstore.

**Expected behavior**
It should pass and successfully upload.

**Smartphone / tablet**
 - OS: Android
 - Package version: ^5.0.2

**Comment by clockwork189** [comment]
I went into the "Flutter Plugins"  section of my project, found "reactive_ble_mobile", navigated to: android>src>main>AndroidManifest.xml
<img width="810" alt="Screen Shot 2022-05-17 at 11 09 38 AM" src="https://user-images.githubusercontent.com/949323/168845245-14294797-c1d3-41aa-bd9d-a0ce6bd496c1.png">
It seems like maxSdkVersion=30 is set for both COARSE and FINE location. 

These are my Manifest permissions, as you can see there is no maxSdkVersion on the fine and coarse location permissions.
<img width="1106" alt="Screen Shot 2022-05-17 at 11 10 36 AM" src="https://user-images.githubusercontent.com/949323/168845453-8ac2f0a1-89bb-46ce-ab83-64d0c10c036e.png">

I tried removing the FINE and COARSE permissions from my Manifest entirely, however the permissions from "reactive_ble_mobile" will clash with other location libraries.

I ended up removing the "maxSdkVersion=30" declaration in Flutter Plugins>reactive_ble_mobile>android>src>main>AndroidManifest.xml then built my app and uploaded it to the playstore and this time I did not get a "Duplicate declarations of permission android.permission.ACCESS_COARSE_LOCATION with different maxSdkVersions" error, which is how I pin pointed this issue to this library. My current workaround works but I am afraid that it will get reset the next time i do a flutter clean + flutter pub get.

**Comment by rickcasson** [comment]
It looks like this issue was fixed on the master branch, but was never published...
Try pointing the plugin directly to the repo master branch and see if that fixes it:

```
  flutter_reactive_ble:
    git:
      url: git@github.com:PhilipsHue/flutter_reactive_ble.git
      path: packages/flutter_reactive_ble
      ref: master
```
You will also need to override the package dependencies:

```
dependency_overrides:
  reactive_ble_mobile:
    git:
      url: git@github.com:PhilipsHue/flutter_reactive_ble.git
      path: packages/reactive_ble_mobile
      ref: master
  reactive_ble_platform_interface:
    git:
      url: git@github.com:PhilipsHue/flutter_reactive_ble.git
      path: packages/reactive_ble_platform_interface
      ref: master
```
